queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check bcachefs [x86_64-linux]
      - check-success=check boot-raid1 [x86_64-linux]
      - check-success=check btrfs-subvolumes [x86_64-linux]
      - check-success=check cli [x86_64-linux]
      - check-success=check complex [x86_64-linux]
      - check-success=check gpt-bios-compat [x86_64-linux]
      - check-success=check hybrid [x86_64-linux]
      - check-success=check hybrid-tmpfs-on-root [x86_64-linux]
      - check-success=check legacy-table [x86_64-linux]
      - check-success=check luks-lvm [x86_64-linux]
      - check-success=check lvm-raid [x86_64-linux]
      - check-success=check lvm-sizes-sort [x86_64-linux]
      - check-success=check mdadm [x86_64-linux]
      - check-success=check module [x86_64-linux]
      - check-success=check multi-device-no-deps [x86_64-linux]
      - check-success=check negative-size [x86_64-linux]
      - check-success=check shellcheck [x86_64-linux]
      - check-success=check simple-efi [x86_64-linux]
      - check-success=check standalone [x86_64-linux]
      - check-success=check swap [x86_64-linux]
      - check-success=check tmpfs [x86_64-linux]
      - check-success=check with-lib [x86_64-linux]
      - check-success=check zfs [x86_64-linux]
      - check-success=check zfs-over-legacy [x86_64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=package disko [x86_64-linux]
      - check-success=package disko-doc [x86_64-linux]
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label=merge-queue
    actions:
      queue: {}
