#!/usr/bin/env bash
set -euo pipefail

readonly libexec_dir="${0%/*}"

# a file with the disko config
declare disko_config

# mount was chosen as the default mode because it's less destructive
mode=mount
nix_args=()

showUsage() {
  cat <<USAGE
Usage: $0 [options] disk-config.nix

Options:

* -m, --mode mode
  set the mode, either create or mount
* --arg name value
  pass value to nix-build. can be used to set disk-names for example
* --argstr name value
  pass value to nix-build as string
USAGE
}

abort() {
  echo "aborted: $*" >&2
  exit 1
}

## Main ##

[[ $# -eq 0 ]] && {
  showUsage
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -m | --mode)
      mode=$2
      shift
      ;;
    --argstr | --arg)
      nix_args+=("$1" "$2" "$3")
      shift
      shift
      ;;
    --help)
      showUsage
      exit 0
      ;;
    *)
      if [ -z ${disko_config+x} ] && [ -e "$1" ]; then
        disko_config=$1
      else
        showUsage
        exit 1
      fi
      ;;
  esac
  shift
done

if ! ([[ $mode = "create" ]] || [[ $mode = "mount" ]]); then
  abort "mode must be either create or mount"
fi

script=$(nix-build "${libexec_dir}"/cli.nix \
  --arg diskoFile "$disko_config" \
  --argstr mode "$mode" \
  "${nix_args[@]}"
)
exec "$script"
