#!/bin/sh
set -efux
# dependencies: bash jq util-linux lvm2 mdadm zfs
disk=$(realpath "$1")

lsblk -a -f >/dev/stderr
lsblk --output-all --json | jq -r --arg disk_to_clear "$disk" -f "$(dirname "$0")/disk-deactivate.jq" | bash -x
lsblk -a -f >/dev/stderr
