{
  pkgs ? import <nixpkgs> { },
}:
let
  # This is a base64-encoded random number. It was generated by running this
  # command:
  #
  # python -c '
  # import base64
  # import random
  # print(base64.b64encode(random.randbytes(32)).decode(encoding="utf_8"))
  # '
  successfulInstallSignal = "q6veJrLaLyBqlcKERGYScr/ygC2buxA9ZpJgnkwjVlA=";
in
pkgs.testers.runNixOSTest {
  name = "disko-unattended-install-iso-test";
  nodes.main =
    { modulesPath, pkgs, ... }:
    {
      virtualisation = {
        libvirtd.enable = true;
        diskSize = 4 * 1024;
        memorySize = 3 * 1024;
      };
      environment = {
        # This is needed for the virt-install and virsh commands.
        systemPackages = [ pkgs.virt-manager ];

        etc."unattended-install.iso".source =
          let
            deployeeConfiguration = import "${modulesPath}/.." {
              configuration = {
                imports = [ ./deployee.nix ];
                inherit successfulInstallSignal;
              };
              inherit (pkgs.stdenv.hostPlatform) system;
            };
            isoPackage = deployeeConfiguration.config.system.build.images.disko-unattended-install-iso;
          in
          "${isoPackage}/iso/${isoPackage.isoName}";
      };
    };

  testScript = ''
    successful_install_signal = "${successfulInstallSignal}"
    deployee_vm_log = main.succeed(
      "virt-install"
      " --osinfo nixos-unstable"
      " --name deployee"
      " --memory 2048"
      " --boot uefi"
      " --disk size=3"
      # This next line disables networking. If we didn’t explicitly disable
      # networking here, then we would need to run another command that starts
      # the default network. We don’t actually need networking for anything, so
      # it’s better to just disable it.
      " --network none"
      " --cdrom /etc/unattended-install.iso"
      " --autoconsole text"
      # This next part makes it so that any text that virt-install prints to
      # stdout will get printed to both stdout and stderr at the same time.
      # Text that goes to stdout will get captured and put in the
      # deployee_vm_log variable. Text that goes to stderr will not be captured
      # and will be printed as a part of the test’s build logs. We want the
      # text to be printed as a part of the test’s build logs so that people
      # can see that the test is indeed making progress while it’s running.
      " | tee >(cat 1>&2)"
    )
    main.succeed('test "$(virsh domstate deployee)" = "shut off"')
    assert successful_install_signal in deployee_vm_log
  '';
}
